version: '2'
services:
  pg-batch:
    image: pg-docker:v1
    ports:
      - "6661:5432"
    environment:
      POSTGRES_USER: user-batch
      POSTGRES_PASSWORD: batch
      POSTGRES_DB: db-batch
    volumes:
      - ./db_batch:/var/lib/postgresql/data

  pg-real:
    image: pg-docker:v1
    ports:
      - "6662:5432"
    environment:
      POSTGRES_USER: user-real
      POSTGRES_PASSWORD: real
      POSTGRES_DB: db-real
    volumes:
      - ./db_real:/var/lib/postgresql/data

  pg-inmutable:
    image: pg-docker:v1
    ports:
      - "6663:5432"
    environment:
      POSTGRES_USER: user-inmutable
      POSTGRES_PASSWORD: inmutable
      POSTGRES_DB: db-inmutable
    volumes:
      - ./db_inmutable:/var/lib/postgresql/data
